name: Gatsby Publish

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FONTS_URL: /jz/fonts/fonts.css
      TYPEKIT_ID: ${{ secrets.TYPEKIT_ID }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths


